GET http://localhost:8080/TestService/call?name=21

###
GET http://localhost:8080/TestService/haha
Content-Type: application/json

{
  "author": "lanicc"
}


###
GET http://localhost:8080/TestService/haha2?name=lanicc
Content-Type: application/json

{
  "author": "lanicc",
  "call": 1111
}
